### PR TITLE
Port generic etg to x86 64

### LINKED ISSUE #2: Hit effects are oversized
And also the colors are wrong (shifted?), but that might be an other issue.

The following screenshot shows a simple bullet hit effect that is grossly oversized.

screenshot from 2019-02-12 14-28-01

I have tracked the code to the `ETG.c` file (**E**ffects of **T**he **G**ods). It would appear there is some assembly magic involved in executing the compiled effect bytecode.

I don't know to what point I can debug that...

### LINKED ISSUE #4: Porting Generic ETG code to x86_64
Following #2, I'm trying to port the generic etg code to x86_64.

The code compiles and works fine on x86 (so my hopes are high).

On 64b it compiles as well but when it tries to run the first hit effect, it segfaults.

### PR DESCRIPTION
**Pull request by ThibaultLemaire**
After a month of trial, error, archeology, debugging, and head scratching,

the generic C code for ETG effects is compiling and running in 64b!

Screenshot from 2019-03-12 14-38-14

The screenshot may not look very impressive, but this is it: the intended behaviour, in 64b. No more huge green explosions, and no segfaults (so far).

Closes #4 

Closes #2

### CODE REVIEW

File: src/Game/ETG.c [hunk 1]
```diff
@@ -6166,21 +6095,16 @@ sdword etgFunctionCall(Effect *effect, struct etgeffectstatic *stat, ubyte *opco
 
     if ((memsize)((etgfunctioncall *)opcode)->function == (memsize) etgSpawnNewEffect){
 
-//        dbgMessagef("Function: %lx:%d   -> %s",((etgfunctioncall *)opcode)->function, nParams+((etgfunctioncall *)opcode)->passThis ,  stat->name);
-
         switch  (nParams+((etgfunctioncall *)opcode)->passThis){
```
Comment (ohemelaar) [inline src/Game/ETG.c:6098]: Maybe it's not relevant to this MR, but this seems like it could be refactored like you did with the other switch statement in `wrapped_unlisted_functions.h`, right?

**Comment by ohemelaar** [comment]
Otherwise it compiles, runs and works on my side, nice!

File: src/Game/ETG.c (hunk 1 above)
Comment (ThibaultLemaire) [reply src/Game/ETG.c:6098]: Yes well, as you can see on line 5983, this is the x86_64 specific code, and indeed the switch cases do look alike. I suspect the generic code was inspired by this one.

With `--enable-generic-etg` this code isn't even compiled, so I didn't bother. Actually, since the generic code works better than this assembly code now, I was even considering deprecating this.

As for the commented code that I deleted, I needed to prune it so I could compare the two versions side by side without useless clutter (the generic one and the x86_64 one).
