### PR TITLE
Fix game hangs on quit in x86_64

### LINKED ISSUE #6: Game hangs on quit with linuxfixme disabled
I know that's the point of having fixmes: to work around code that doesn't work.

But in x86_64 the game is generally more stable with fixmes disabled. Except it doesn't quit.

If this was fixed, I would consider the game playable enough to designate a 1.0.0 release.

### PR DESCRIPTION
**Pull request by ThibaultLemaire**
This should make the game stable enough with Linux fixmes disabled.

Closes #6

### CODE REVIEW

File: src/SDL/utility.c [hunk 1]
```diff
@@ -3510,24 +3510,24 @@ void utyGrowthHeapFree(void *heap)
 char *utyMissingCDMessages[] =
 {
     "Invalid or missing Homeworld CD. Please insert valid CD.",
-    "CD Homeworld non valide. Veuillez ins�rer un CD valide.",
```
Comment (ohemelaar) [inline src/SDL/utility.c:3513]: You somehow broke the encoding : Accent show up nicely before, and appear as an � after.

Comment (ohemelaar) [reply src/SDL/utility.c:3513]: Original encoding seems to be Windows 1252

**Review by ohemelaar — APPROVED** [review]
